[tool.poetry]
name = "abstractsprogramming"
version = "0.1.0"
description = ""
authors = ["Kolodkin.SS"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
yappi = "^1.6.0"
snakeviz = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
